// xmpp/build.gradle.kts - generated by tools/split-modules from tools/modules.toml
// namespace uk.xa0.tulkki.xmpp (docs/MIGRATION.md "The module map" §4.2: R and .databinding follow the namespace, and two
// modules may not generate the same R/BuildConfig FQN)

import com.google.common.base.CaseFormat
import io.github.classgraph.AnnotationInfo
import io.github.classgraph.ClassGraph
import io.github.classgraph.ClassInfo

apply(plugin = "com.android.library")

// ---------------------------------------------------------------------------------------------
// The extension index.
//
// `ExtensionFactory` turns an element name + namespace into a model class, and both directions of
// that lookup used to come out of a javac annotation processor's generated
// `Extensions.EXTENSION_CLASS_MAP`. A javac processor cannot see Kotlin, so every model that
// converted had to be written a second time into a hand-maintained `ModelRegistry` - two maps for
// one fact, kept in step by hand. ClassGraph reads *classfiles*, so it sees the Kotlin and the Java
// models alike and the second map, and its drift, go away.
//
// The task scans the two compiled output trees of the debug variant and writes a sorted TSV,
// `namespace \t name \t binary-class`, with a `# tulkki-extension-index/1` header. Two details are
// load-bearing:
//
//  * the class is stored in its **binary** spelling (`Outer$Inner`). ClassGraph's
//    `ClassInfo.getName()` differs from the processor's `getQualifiedName()` for the nested
//    `error.Condition.*` and `sasl.SaslError.*` types, and `Class.forName` needs the `$` form.
//  * the file lands as a **java resource** (`variant.sources.resources` in the Variant API; the
//    legacy `sourceSets.main.resources` route is refused by AGP 9), read by `Class.getResourceAsStream`.
//    That is Context-free and needs no post-compile `aapt2` injection, so it cannot race AGP 9's
//    merge -> link -> compile order.
//
// `enableClasspathEntries` does not exist in ClassGraph 4.8.197 -- the wiki's recipe is wrong for
// the pinned version -- so the classpath is `overrideClasspath` over the two class dirs. ClassGraph
// and Guava come from the root buildscript's classpath (build.gradle.kts).
// ---------------------------------------------------------------------------------------------

val generateExtensionIndex = tasks.register<GenerateExtensionIndex>("generateExtensionIndex") {
    group = "build"
    description = "Writes the @XmlElement extension index as a java resource for ExtensionFactory"
    // The two compiled trees AGP produces for this variant, named exactly as AGP lays them out
    // (`javac/<variant>/<task>/classes` and `built_in_kotlinc/<variant>/<task>/classes`) and
    // ordered by `dependsOn`, which is resolved lazily at task-graph time and so cannot fail this
    // script's configuration. Reading the dirs off the tasks (`outputs.files`) would be less
    // coupled to AGP, but a Kotlin task that declared no output directory would then scan the Java
    // tree alone and write 120 plausible rows with nothing to warn anyone; here an absent tree is a
    // hard failure instead.
    dependsOn("compileDebugJavaWithJavac", "compileDebugKotlin")
    javaClassDirs.from(
        project.layout.buildDirectory.dir(
            "intermediates/javac/debug/compileDebugJavaWithJavac/classes"
        )
    )
    kotlinClassDirs.from(
        project.layout.buildDirectory.dir(
            "intermediates/built_in_kotlinc/debug/compileDebugKotlin/classes"
        )
    )
    outputDir.set(project.layout.buildDirectory.dir("generated/extensionIndex"))
}

configure<com.android.build.api.dsl.LibraryExtension> {
    namespace = "uk.xa0.tulkki.xmpp"
    compileSdk = 36
    defaultConfig {
        buildConfigField("String", "APP_NAME", "\"${rootProject.extra["appName"]}\"")
        buildConfigField("String", "VERSION_NAME", "\"${rootProject.extra["versionName"]}\"")
        // AGP 9's public library DSL has no `targetSdk` member: the Groovy `targetSdkVersion 36`
        // here landed on the legacy `BaseFlavor.targetSdkVersion(int)` through the closure's runtime
        // delegate, and a library's AAR carries none. Left out rather than emulated - reported.
        minSdk = 23
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig = true
    }
    lint {
        disable += listOf("MissingTranslation", "InvalidPackage", "AppCompatResource")
        abortOnError = false
    }
}

// The index is read by name at runtime, so it must travel in the APK as a **java resource** -
// `Class.getResourceAsStream`, not `res`/aapt2 - and the task that writes it must run after both
// compile tasks. AGP 9 refuses the legacy route: `sourceSets.main.resources.srcDir(<task provider>)`
// fails at configuration with "You cannot add Provider instances to the Android SourceSet API".
// The Variant API is the supported wire, and `addGeneratedSourceDirectory` carries both halves the
// legacy call did not: it makes the resource-consuming task depend on `generateExtensionIndex` *and*
// reads the directory from its `@OutputDirectory` property. `variant.sources.resources` is the
// java-resource source set (never `sources.res`, the aapt2 one). The escape hatch AGP's error offers
// (`android.sourceset.disallowProvider=false`) is deliberately not taken: it silences the check while
// leaving the dependency uncarried, which is the ordering bug the check exists to prevent.
configure<com.android.build.api.variant.LibraryAndroidComponentsExtension> {
    onVariants(selector().all()) { variant ->
        variant.sources.resources?.addGeneratedSourceDirectory(generateExtensionIndex) { task ->
            task.outputDir
        }
    }
}

dependencies {
    "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.1.5")
    // The `@XmlElement` annotations the models carry. Nothing here is an `annotationProcessor` any
    // more: the aggregating index is built by `generateExtensionIndex`, from the compiled classes.
    "implementation"(project(":libs:annotation"))
    "implementation"("androidx.annotation:annotation:1.9.1")
    "implementation"("androidx.core:core:1.18.0")
    "implementation"("androidx.preference:preference:1.2.1")
    "implementation"("androidx.sqlite:sqlite:2.6.2")
    "implementation"("com.squareup.okhttp3:okhttp:4.12.0")
    "implementation"("com.squareup.retrofit2:retrofit:3.0.0")
    "implementation"("net.fellbaum:jemoji:1.7.6")
    "implementation"("net.zetetic:sqlcipher-android:4.16.0@aar")
    "implementation"("androidx.appcompat:appcompat:1.7.1")
    "implementation"("androidx.recyclerview:recyclerview:1.4.0")
    "implementation"("com.caverock:androidsvg-aar:1.4")
    "implementation"("com.github.ipld:java-cid:v1.3.1")
    "api"("com.github.open-keychain.open-keychain:openpgp-api:v5.7.1")
    "implementation"("com.github.singpolyma:OpenGraphParser:d0882eadb2")
    "implementation"("com.google.android.material:material:1.14.0")
    "implementation"("com.google.guava:guava:33.6.0-android")
    "implementation"("im.conversations.webrtc:webrtc-android:129.0.0")
    "implementation"("io.deepmedia.community:transcoder-android:0.11.2")
    "implementation"("me.drakeet.support:toastcompat:1.1.0")
    "implementation"("me.leolin:ShortcutBadger:1.1.22@aar")
    "implementation"("org.bouncycastle:bcmail-jdk18on:1.84")
    "implementation"("org.conscrypt:conscrypt-android:2.5.3")
    "implementation"("org.jitsi:org.otr4j:0.23")
    // The resolver: minidns moved from 128 vendored files under this module's source set to the
    // released 1.1.1 artifacts. `api` because the vendored classes used to be *this module's own
    // output*, so every consumer could see them; `Resolver.Result.getHostname()` returns a
    // `org.minidns.dnsname.DnsName` in a public signature, which is the sharp end of the same fact.
    // `minidns-android23` is the Android variant carrying dnsserverlookup/android21.
    "api"("org.minidns:minidns-core:1.1.1")
    "api"("org.minidns:minidns-client:1.1.1")
    "api"("org.minidns:minidns-async:1.1.1")
    "api"("org.minidns:minidns-dnssec:1.1.1")
    "api"("org.minidns:minidns-dane:1.1.1")
    "api"("org.minidns:minidns-hla:1.1.1")
    "api"("org.minidns:minidns-iterative-resolver:1.1.1")
    "api"("org.minidns:minidns-android23:1.1.1")
    "implementation"("org.jxmpp:jxmpp-jid:1.1.0")
    "implementation"("org.jxmpp:jxmpp-stringprep-libidn:1.1.0")
    "implementation"("org.whispersystems:signal-protocol-java:2.6.2")
    // The module's first JVM test: `SaslMechanismEnsureAvailableTest` pins the half of the device
    // crash a handshake-free cell can reach. This is the line `tools/split-modules`'
    // TEST_DEPENDENCIES emits for a module whose tests import `org.junit`.
    "testImplementation"("junit:junit:4.13.2")
}

/**
 * Scans the compiled model classes for `@XmlElement` and writes the sorted extension index.
 *
 * <p>Two of the annotation processor's guards survive as **build failures**, because both are
 * silent at runtime: a type that declares no namespace would produce an entry nobody can ever
 * resolve, and a type without a public no-arg constructor would produce an entry that resolves and
 * then throws. A third guard has no processor predecessor but the same silence: two types claiming
 * one `(name, namespace)` pair - the processor's `ImmutableSortedMap.Builder` refused that
 * outright, and a map built from a file would simply keep the last one.
 */
abstract class GenerateExtensionIndex : DefaultTask() {

    companion object {
        private const val INDEXED_PACKAGE = "uk.xa0.tulkki.xmpp.models"
        private const val XML_ELEMENT = "uk.xa0.tulkki.annotation.XmlElement"
        private const val HEADER = "# tulkki-extension-index/1"
        private const val RESOURCE_PATH = "uk/xa0/tulkki/xmpp/models/extension-index.txt"
    }

    /** `:xmpp`'s javac output: the models that are still Java. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val javaClassDirs: ConfigurableFileCollection

    /** `:xmpp`'s Kotlin output. A separate input because the scan must never silently lose it. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val kotlinClassDirs: ConfigurableFileCollection

    /** The java-resource tree `sourceSets.main.resources` consumes. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val classpath = mutableListOf<File>()
        for (tree in listOf("java", "kotlin")) {
            val dirs = mutableListOf<File>()
            val entries = if (tree == "java") javaClassDirs.files else kotlinClassDirs.files
            for (entry in entries) {
                if (entry.isDirectory) {
                    dirs.add(entry)
                }
            }
            if (dirs.isEmpty()) {
                throw GradleException(
                    "generateExtensionIndex: the $tree class dir is empty or unreadable. Scanning " +
                        "only the other tree would write an index with entries missing, and nothing " +
                        "at runtime would warn you; the wiring of compileDebugJavaWithJavac / " +
                        "compileDebugKotlin is the thing to check."
                )
            }
            classpath.addAll(dirs)
        }
        val rows = mutableListOf<String>()
        val claimed = mutableMapOf<String, String>()
        val classGraph = ClassGraph()
            .overrideClasspath(classpath)
            .acceptPackages(INDEXED_PACKAGE)
            .enableClassInfo()
            .enableAnnotationInfo()
            .enableMethodInfo()
        classGraph.scan().use { scanResult ->
            for (classInfo in scanResult.getClassesWithAnnotation(XML_ELEMENT)) {
                val element: AnnotationInfo =
                    classInfo.getAnnotationInfo(XML_ELEMENT) ?: continue
                val namespace = string(element, "namespace")
                if (namespace.isNullOrEmpty()) {
                    throw GradleException(
                        "generateExtensionIndex: ${classInfo.name} declares no namespace. " +
                            "@XmlElement.namespace() is the only source now that @XmlPackage is " +
                            "gone, so this type could never be resolved by name."
                    )
                }
                var name = string(element, "name")
                if (name.isNullOrEmpty()) {
                    name = CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_HYPHEN, classInfo.simpleName)
                }
                if (!hasPublicNoArgConstructor(classInfo)) {
                    throw GradleException(
                        "generateExtensionIndex: ${classInfo.name} has no public no-arg " +
                            "constructor, so the index would carry an entry ExtensionFactory " +
                            "cannot instantiate."
                    )
                }
                val key = namespace + "\t" + name
                val previous = claimed.put(key, classInfo.name)
                if (previous != null) {
                    throw GradleException(
                        "generateExtensionIndex: $previous and ${classInfo.name} both claim the " +
                            "($name, $namespace) pair, so one of them would silently never resolve."
                    )
                }
                rows.add(key + "\t" + classInfo.name)
            }
        }
        if (rows.isEmpty()) {
            throw GradleException(
                "generateExtensionIndex: no @XmlElement classes were found in $classpath. A green " +
                    "build here would ship an index that resolves nothing; the compiled class dirs " +
                    "are the thing to check."
            )
        }
        rows.sort()
        val target = File(outputDir.get().asFile, RESOURCE_PATH)
        target.parentFile.mkdirs()
        target.writeText(HEADER + "\n" + rows.joinToString("\n") + "\n", Charsets.UTF_8)
        logger.lifecycle("generateExtensionIndex: ${rows.size} entries -> $target")
    }

    private fun string(annotation: AnnotationInfo?, parameter: String): String? {
        val values = annotation?.parameterValues ?: return null
        return values.getValue(parameter)?.toString()
    }

    private fun hasPublicNoArgConstructor(classInfo: ClassInfo): Boolean {
        for (constructor in classInfo.constructorInfo) {
            if (constructor.isPublic && constructor.parameterInfo.isEmpty()) {
                return true
            }
        }
        return false
    }
}
