// app/build.gradle.kts - generated by tools/split-modules from tools/modules.toml
// namespace uk.xa0.tulkki.app (docs/MIGRATION.md "The module map" §4.2: R and .databinding follow the namespace, and two
// modules may not generate the same R/BuildConfig FQN)

import java.util.Properties

apply(plugin = "com.android.application")

// docs/MIGRATION.md "The module map" §4.6 hoists `ext.abiCodes`, `splits.abi` and the versionCode block into
// :app together, and the root block they come from (build.gradle:151-154) sits *before*
// its `android {}` (build.gradle:156).  The order is load-bearing: inside :app
// `project.ext` is :app's own -- a root-level `ext` is not read here -- and an `ext`
// emitted after `android {}` is `Cannot get property 'abiCodes' on extra properties
// extension as it does not exist`, at configuration, before a single task runs.
// (Kotlin DSL: a plain top-level `val`, so the one reader below cannot see it unset either.)
val abiCodes: Map<String, Int> =
    mapOf("armeabi-v7a" to 1, "x86" to 2, "x86_64" to 3, "arm64-v8a" to 4)

configure<com.android.build.api.dsl.ApplicationExtension> {
    namespace = "uk.xa0.tulkki.app"
    compileSdk = 36
    defaultConfig {
        minSdk = 23
        targetSdk = 36
        // The applicationId stays uk.xa0.tulkki and stays in :app only. Changing it is
        // a different app: the SQLCipher database, the Keystore-backed key and the OMEMO
        // identity all become invisible. tools/rename-packages protects the whole line.
        applicationId = "uk.xa0.tulkki"
        versionCode = rootProject.extra["versionCode"] as Int
        versionName = rootProject.extra["versionName"] as String
        resValue("string", "app_name", rootProject.extra["appName"] as String)
        buildConfigField("String", "APP_NAME", "\"${rootProject.extra["appName"]}\"")
        buildConfigField("String", "PRIVACY_POLICY", "${rootProject.extra["privacyPolicy"]}")
        // build.gradle:179: a defaultConfig property.  It is not a dependency and Gradle
        // refuses the whole script if it is written inside `dependencies {}`.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig = true
        dataBinding = true
        resValues = true
    }
    lint {
        disable += listOf("MissingTranslation", "InvalidPackage", "AppCompatResource")
        abortOnError = false
    }
    // The NDK is gone: the six image filters are absorbed into
    // uk.xa0.tulkki.ui.imaging.ImageFilters (port-16) and there is no other native code we build.
    // §4.6: rootProject.file(...) or the path resolves to app/ and AGP signs with the
    // debug key in silence, which only the phone reveals.
    if (rootProject.file("signing.properties").exists()) {
        val props = Properties()
        rootProject.file("signing.properties").inputStream().use { props.load(it) }
        signingConfigs {
            create("release") {
                storeFile = rootProject.file(props.getProperty("keystore"))
                storePassword = props.getProperty("keystore.password")
                keyAlias = props.getProperty("keystore.alias")
                keyPassword = props.getProperty("keystore.password")
            }
        }
        buildTypes {
            maybeCreate("release").signingConfig = signingConfigs.getByName("release")
            maybeCreate("debug").signingConfig = signingConfigs.getByName("release")
        }
    }
    flavorDimensions += "app"
    productFlavors {
        create("tulkki") {
            dimension = "app"
            applicationId = "uk.xa0.tulkki"
        }
    }
    // build.gradle:187-200: the task-name sniff is what keeps an iterating debug build to
    // one APK.  Without it every variant is universal and a release ships one APK where five
    // are expected (AGENTS.md: release is unverified here; this line is lifted from the
    // monolith, not measured by a release run).
    splits {
        abi {
            val iterating = gradle.startParameter.taskNames.any { it.lowercase().contains("debug") }
            isUniversalApk = true
            isEnable = !iterating
            reset()
            include(*abiCodes.keys.toTypedArray())
        }
    }
    packaging {
        resources {
            excludes += listOf(
                "META-INF/BCKEY.DSA", "META-INF/BCKEY.SF",
                "META-INF/versions/9/OSGI-INF/MANIFEST.MF", "META-INF/LICENSE.md",
                "META-INF/LICENSE-notice.md", "META-INF/DEPENDENCIES"
            )
        }
    }
    buildTypes {
        release {
            isShrinkResources = true
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                rootProject.file("proguard-rules.pro")
            )
        }
    }
}

// §4.6: the applicationId resValue is :app's, and nowhere else.
// root-2: the `100 * versionCode + abiCode` output override is retired at the orphan
// root.  Every output keeps `defaultConfig`'s plain `rootProject.ext.versionCode` (1),
// so a debug build no longer sorts above a release APK: both carry the release key, and
// either replaces the other only at an equal versionCode, with a downgrade still refused.
configure<com.android.build.api.variant.ApplicationAndroidComponentsExtension> {
    onVariants(selector().all()) { variant ->
        variant.resValues.put(
            variant.makeResValueKey("string", "applicationId"),
            variant.applicationId.map { id -> com.android.build.api.variant.ResValue(id, null) }
        )
    }
}

dependencies {
    "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.1.5")
    "implementation"(project(":crypto"))
    "implementation"(project(":data"))
    "implementation"(project(":translation"))
    "implementation"(project(":ui"))
    "implementation"(project(":xmpp"))
    "implementation"(project(":libs:annotation"))
    "implementation"("androidx.annotation:annotation:1.9.1")
    "implementation"("androidx.core:core:1.18.0")
    "implementation"("androidx.emoji2:emoji2-bundled:1.6.0")
    "implementation"("androidx.emoji2:emoji2-emojipicker:1.6.0")
    "implementation"("androidx.emoji2:emoji2:1.6.0")
    "implementation"("androidx.media3:media3-exoplayer:1.10.1")
    "implementation"("androidx.media3:media3-session:1.10.1")
    "implementation"("androidx.media3:media3-ui:1.10.1")
    "implementation"("androidx.preference:preference:1.2.1")
    "implementation"("androidx.sqlite:sqlite:2.6.2")
    "implementation"("com.leinardi.android:speed-dial:3.3.0")
    "implementation"("com.squareup.okhttp3:okhttp:4.12.0")
    "implementation"("com.squareup.retrofit2:converter-gson:3.0.0")
    "implementation"("com.squareup.retrofit2:retrofit:3.0.0")
    "implementation"("net.zetetic:sqlcipher-android:4.16.0@aar")
    "implementation"("androidx.appcompat:appcompat:1.7.1")
    "implementation"("androidx.documentfile:documentfile:1.1.0")
    "implementation"("androidx.recyclerview:recyclerview:1.4.0")
    "implementation"("androidx.work:work-runtime:2.11.2")
    "implementation"("com.github.bumptech.glide:annotations:4.16.0")
    "implementation"("com.github.bumptech.glide:glide:4.16.0")
    "implementation"("com.github.chrisbanes:PhotoView:2.3.0")
    "implementation"("com.github.ipld:java-cid:v1.3.1")
    "implementation"("com.google.android.material:material:1.14.0")
    "implementation"("com.google.guava:guava:33.6.0-android")
    "implementation"("com.google.zxing:core:3.5.4")
    "implementation"("im.conversations.webrtc:webrtc-android:129.0.0")
    "implementation"("io.deepmedia.community:transcoder-android:0.11.2")
    "implementation"("io.github.nishkarsh:android-permissions:2.1.8")
    "implementation"("io.michaelrocks:libphonenumber-android:8.13.52")
    "implementation"("me.drakeet.support:toastcompat:1.1.0")
    "implementation"("me.xdrop:fuzzywuzzy:1.4.0")
    "implementation"("org.bouncycastle:bcmail-jdk18on:1.84")
    "implementation"("com.github.bumptech.glide:okhttp3-integration:4.16.0") {
        exclude(group = "glide-parent")
    }
    // docs/MIGRATION.md "The module map" §4.2: this module declares the @GlideModule, so Glide's
    // compiler generates GlideApp into *this* compilation
    "annotationProcessor"("com.github.bumptech.glide:compiler:4.16.0")
    "testImplementation"("junit:junit:4.13.2")
    // port-16's last argon2 gate: the published argon2kt binaries can only run on a device, so the
    // known-answer check is an instrumented test (app/src/androidTest/.../Argon2DeviceKnownAnswerTest).
    "androidTestImplementation"("androidx.test.ext:junit:1.2.1")
    "androidTestImplementation"("androidx.test:runner:1.6.2")
    "testImplementation"("org.junit.jupiter:junit-jupiter:5.12.2")
    "testImplementation"("com.squareup.okhttp3:mockwebserver:4.12.0")
}
