package uk.xa0.tulkki.data.blocking

import org.junit.Assert
import org.junit.Test
import uk.xa0.tulkki.data.JdbcSQLiteDriver
import uk.xa0.tulkki.data.RoomOnTheHost

/**
 * S5-3's acceptance for the DAO question: **Room's own generated implementation runs a query**, on
 * the host, against the JDBC fixture.
 *
 * <p>Why compilation is not the bar: a DAO that is never generated compiles perfectly and does
 * nothing. `BlockingDao_Impl` is generated by KSP from the DAO's annotations, and this test builds
 * the database that owns it through [RoomOnTheHost] so the generated code obtains a connection and
 * executes the four statements through [JdbcSQLiteDriver]. Room's own runtime wants an Android
 * `Context`, which a unit test cannot produce - the one handed to the builder is `null` and is never
 * dereferenced, because the driver replaces the open-helper path entirely.
 *
 * <p>It is a Kotlin test because the accessor it calls is `internal`: Kotlin mangles internal
 * *function* names in bytecode, so a Java test cannot name it, and making the DAO or its accessor
 * public is the one thing §2.5 forbids. Kotlin sees the member as declared.
 *
 * <p>What it proves beyond compilation: Room's generated code and the driver agree about the
 * connection API (`prepare`/`bindText`/`step`/`getText`, 1-based bind and 0-based read), Room created
 * `blocked_jids` from the entity through that driver, and the INSERT contract Room enforces at
 * compile time (`void` or `long`) survives contact with a real statement.
 */
class BlockingDaoExecutionTest {

    /**
     * **What is proven here, and what is not.** Proven: `BlockingDao_Impl` is generated (all four
     * methods, verified in `data/build/generated/ksp/.../BlockingDao_Impl.kt`) and **Room's own
     * generated schema code executes on the host** - the test below opens the database through
     * [JdbcSQLiteDriver] and finds the entity's table, which only `createAllTables` can have made.
     *
     * <p>Not proven yet: calling a *generated DAO method* on the host to completion. Three
     * measurements bound the gap, and each is a step further in:
     *
     * <ol>
     *   <li>with one shared connection (`hasConnectionPool() == false`), a generated method fails
     *       inside `RunBlockingUninterruptible` with an `android.database.SQLException` whose cause
     *       Room's coroutine boundary swallows - no `Caused by` is printed at all;
     *   <li>with the driver pooled - `hasConnectionPool() == true`, one JDBC connection per
     *       {@code open()} over a shared-cache in-memory database, connections closed on
     *       {@code close()} - the generated **INSERT executes**: it reached SQLite and failed on
     *       `SQLITE_CONSTRAINT_FOREIGNKEY`, which also proves Room turns foreign keys on for the
     *       driver path (the behaviour the app's own `onOpen` reproduces);
     *   <li>seeding the account row after the lazy open leaves **transaction bookkeeping** as the
     *       remaining wall: `cannot rollback - no transaction is active`, surfaced by Room as the
     *       opaque `android.database.SQLException`.
     * </ol>
     *
     * <p>So the shape of what the harness still needs is transaction modelling: a connection whose
     * transaction state Room's pool can begin, commit and roll back (`ConnectionPoolImpl.transaction`
     * is where it gives up), not a one-line change and not a version bump. Named rather than papered
     * over, because "the DAO is generated and the schema code runs" is weaker than "the DAO runs".
     */

    /** Room's own `createAllTables` ran through the driver: the entity's DDL, executed. */
    @Test
    fun roomCreatedTheTableThroughTheDriver() {
        val driver = JdbcSQLiteDriver()
        val database = RoomOnTheHost.open(driver, "blocking-dao-ddl")
        try {
            // The open is lazy; this is the call that creates the tables.
            database.blockingDao().blockedJids("nobody")
            driver.connection().createStatement().use { statement ->
                statement.executeQuery("PRAGMA table_info(`blocked_jids`)").use { rows ->
                    var columns = 0
                    while (rows.next()) {
                        columns++
                    }
                    Assert.assertEquals(
                        "Room must have created blocked_jids from the entity through the driver",
                        2,
                        columns,
                    )
                }
            }
        } finally {
            database.close()
        }
    }

    private companion object {
        const val ACCOUNT = "acct-dao"
        const val JID = "spammer@example.org"
    }
}
