// data/build.gradle.kts - generated by tools/split-modules from tools/modules.toml
// namespace uk.xa0.tulkki.data (docs/MIGRATION.md "The module map" §4.2: R and .databinding follow the namespace, and two
// modules may not generate the same R/BuildConfig FQN)

// S5-1: the first annotation processor in the tree that is not javac's. Room's compiler runs under
// KSP (kapt is ruled out: it runs javac's processing over Kotlin stubs and would collide with the
// in-tree XmlProcessor, which is javac-only and stays javac-only). The version is the independent
// KSP line, not the old `<kotlin>-<ksp>` scheme; 2.3.1 is where AGP 9's built-in Kotlin is
// supported, and 2.3.4 is where the `kotlin.sourceSets` failure with built-in Kotlin is fixed.
plugins {
    id("com.google.devtools.ksp") version "2.3.12"
}

apply(plugin = "com.android.library")

configure<com.android.build.api.dsl.LibraryExtension> {
    namespace = "uk.xa0.tulkki.data"
    compileSdk = 36
    defaultConfig {
        buildConfigField("String", "APPLICATION_ID", "\"${rootProject.extra["appId"]}\"")
        buildConfigField("String", "APP_NAME", "\"${rootProject.extra["appName"]}\"")
        // AGP 9's public library DSL has no `targetSdk` member: the Groovy `targetSdkVersion 36`
        // here landed on the legacy `BaseFlavor.targetSdkVersion(int)` through the closure's runtime
        // delegate, and a library's AAR carries none. Left out rather than emulated - reported.
        minSdk = 23
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig = true
        dataBinding = true
    }
    lint {
        disable += listOf("MissingTranslation", "InvalidPackage", "AppCompatResource")
        abortOnError = false
    }
}

dependencies {
    "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.1.5")
    "api"(project(":crypto")) // tools/modules.toml :data.exposes: this module's API names :crypto's types
    "api"(project(":xmpp")) // tools/modules.toml :data.exposes: this module's API names :xmpp's types
    "implementation"(project(":libs:annotation"))
    "implementation"("androidx.annotation:annotation:1.9.1")
    "implementation"("androidx.core:core:1.18.0")
    "implementation"("androidx.datastore:datastore-preferences:1.2.1")
    "implementation"("androidx.emoji2:emoji2-bundled:1.6.0")
    "implementation"("androidx.emoji2:emoji2-emojipicker:1.6.0")
    "implementation"("androidx.emoji2:emoji2:1.6.0")
    "implementation"("androidx.media3:media3-exoplayer:1.10.1")
    "implementation"("androidx.media3:media3-session:1.10.1")
    "implementation"("androidx.media3:media3-ui:1.10.1")
    "implementation"("androidx.preference:preference:1.2.1")
    "api"("androidx.sqlite:sqlite:2.6.2")
    // S5-1: Room opens the existing file through sqlcipher-android's own
    // SupportOpenHelperFactory. S5-6 adds `room-ktx`: the read models are `Flow`s and the DAO
    // surface now returns them, which is Room's coroutine read - the dependency S5-1 deliberately
    // deferred, because that commit added no suspend or streaming DAO.
    "api"("androidx.room:room-runtime:2.7.0")
    "api"("androidx.room:room-ktx:2.7.0")
    "ksp"("androidx.room:room-compiler:2.7.0")
    "implementation"("com.google.crypto.tink:tink-android:1.21.0")
    "implementation"("com.squareup.retrofit2:converter-gson:3.0.0")
    "api"("net.zetetic:sqlcipher-android:4.16.0@aar")
    "implementation"("androidx.appcompat:appcompat:1.7.1")
    "implementation"("androidx.cardview:cardview:1.0.0")
    "implementation"("androidx.documentfile:documentfile:1.1.0")
    "implementation"("androidx.exifinterface:exifinterface:1.4.2")
    "implementation"("androidx.recyclerview:recyclerview:1.4.0")
    "implementation"("androidx.viewpager:viewpager:1.1.0")
    "implementation"("com.caverock:androidsvg-aar:1.4")
    "implementation"("com.github.ipld:java-cid:v1.3.1")
    "implementation"("com.github.singpolyma:Better-Link-Movement-Method:393d35e453")
    "implementation"("com.github.woltapp:blurhash:master")
    "implementation"("com.google.android.material:material:1.14.0")
    "implementation"("com.google.guava:guava:33.6.0-android")
    "implementation"("io.michaelrocks:libphonenumber-android:8.13.52")
    "implementation"("net.fellbaum:jemoji:1.7.6")
    "implementation"("org.hsluv:hsluv:0.2")
    "implementation"("org.jitsi:org.otr4j:0.23")
    "implementation"("org.jxmpp:jxmpp-jid:1.1.0")
    "implementation"("org.jxmpp:jxmpp-stringprep-libidn:1.1.0")
    "implementation"("org.tomlj:tomlj:1.1.1")
    "implementation"("org.whispersystems:signal-protocol-java:2.6.2")
    "testImplementation"("junit:junit:4.13.2")
    "testImplementation"("org.junit.jupiter:junit-jupiter:5.12.2")
    "testImplementation"("com.squareup.okhttp3:mockwebserver:4.12.0")
    // S5-2: the schema-76 work can only be *executed* on a host through a plain-JVM SQLite
    // (docs/MIGRATION.md, "Design: the data layer" §4.4: SQLCipher ships Android ABIs only, so no
    // JVM test can open the file). Test scope only; nothing here reaches the app.
    "testImplementation"("org.xerial:sqlite-jdbc:3.41.2.2")
    // S5-2: the seed reads `last_clear_history` out of the conversation's attributes JSON, and
    // `org.json` is a platform class on Android but a throwing stub on the host. Test scope only:
    // the device keeps the platform implementation, so what the host parses is what ships.
    "testImplementation"("org.json:json:20240303")
}
