package uk.xa0.tulkki.xml

/**
 * Tulkki: the XMPP namespaces the tree speaks, as compile-time constants.
 *
 * Ported from `Namespace.java`. It is a pure bag of
 * `String` constants with no instance state, so it becomes a Kotlin `object`; each
 * `public static final String` stays a `const val`, which still compiles to the Java-visible
 * `public static final String` field every caller reads (`Namespace.X`), and the derived constants
 * (`AXOLOTL_BUNDLES`, `PUBSUB_EVENT`, `BOOKMARKS2_COMPAT`) stay constant expressions. The public
 * no-arg constructor the Java class had is the one member that goes - it is implicit in Java and
 * nothing constructed it (`new Namespace()` has zero hits tree-wide) - so the checker's allow-list
 * records it.
 */
object Namespace {
    const val ADDRESSING = "http://jabber.org/protocol/address"
    const val AXOLOTL = "eu.siacs.conversations.axolotl"
    const val PGP_SIGNED = "jabber:x:signed"
    const val PGP_ENCRYPTED = "jabber:x:encrypted"
    const val AXOLOTL_BUNDLES = AXOLOTL + ".bundles"
    const val AXOLOTL_DEVICE_LIST = AXOLOTL + ".devicelist"
    const val HINTS = "urn:xmpp:hints"
    const val MESSAGE_ARCHIVE_MANAGEMENT = "urn:xmpp:mam:2"
    const val VERSION = "jabber:iq:version"
    const val LAST_MESSAGE_CORRECTION = "urn:xmpp:message-correct:0"
    const val RESULT_SET_MANAGEMENT = "http://jabber.org/protocol/rsm"
    const val CHAT_MARKERS = "urn:xmpp:chat-markers:0"
    const val CHAT_STATES = "http://jabber.org/protocol/chatstates"
    const val DELIVERY_RECEIPTS = "urn:xmpp:receipts"
    const val REACTIONS = "urn:xmpp:reactions:0"
    const val VCARD_TEMP = "vcard-temp"
    const val VCARD_TEMP_UPDATE = "vcard-temp:x:update"
    const val DELAY = "urn:xmpp:delay"
    const val OCCUPANT_ID = "urn:xmpp:occupant-id:0"
    const val STREAMS = "http://etherx.jabber.org/streams"
    const val STANZAS = "urn:ietf:params:xml:ns:xmpp-stanzas"
    const val JABBER_CLIENT = "jabber:client"
    const val FORWARD = "urn:xmpp:forward:0"
    const val DISCO_ITEMS = "http://jabber.org/protocol/disco#items"
    const val DISCO_INFO = "http://jabber.org/protocol/disco#info"
    const val EXTERNAL_SERVICE_DISCOVERY = "urn:xmpp:extdisco:2"
    const val BLOCKING = "urn:xmpp:blocking"
    const val ROSTER = "jabber:iq:roster"
    const val REGISTER = "jabber:iq:register"
    const val REGISTER_STREAM_FEATURE = "http://jabber.org/features/iq-register"
    const val BYTE_STREAMS = "http://jabber.org/protocol/bytestreams"
    const val HTTP_UPLOAD = "urn:xmpp:http:upload:0"
    const val HTTP_UPLOAD_LEGACY = "urn:xmpp:http:upload"
    const val STANZA_IDS = "urn:xmpp:sid:0"
    const val IDLE = "urn:xmpp:idle:1"
    const val DATA = "jabber:x:data"
    const val OOB = "jabber:x:oob"
    const val SASL = "urn:ietf:params:xml:ns:xmpp-sasl"
    const val SASL_2 = "urn:xmpp:sasl:2"
    const val CHANNEL_BINDING = "urn:xmpp:sasl-cb:0"
    const val FAST = "urn:xmpp:fast:0"
    const val TLS = "urn:ietf:params:xml:ns:xmpp-tls"
    const val PUBSUB = "http://jabber.org/protocol/pubsub"
    const val PUBSUB_EVENT = PUBSUB + "#event"
    const val MUC = "http://jabber.org/protocol/muc"
    const val PUBSUB_PUBLISH_OPTIONS = PUBSUB + "#publish-options"
    const val PUBSUB_CONFIG_NODE_MAX = PUBSUB + "#config-node-max"
    const val PUBSUB_ERROR = PUBSUB + "#errors"
    const val PUBSUB_OWNER = PUBSUB + "#owner"
    const val NICK = "http://jabber.org/protocol/nick"
    const val FLEXIBLE_OFFLINE_MESSAGE_RETRIEVAL =
            "http://jabber.org/protocol/offline"
    const val BIND = "urn:ietf:params:xml:ns:xmpp-bind"
    const val BIND2 = "urn:xmpp:bind:0"
    const val STREAM_MANAGEMENT = "urn:xmpp:sm:3"
    const val CSI = "urn:xmpp:csi:0"
    const val CARBONS = "urn:xmpp:carbons:2"
    const val BOOKMARKS_CONVERSION = "urn:xmpp:bookmarks-conversion:0"
    const val BOOKMARKS = "storage:bookmarks"
    const val SYNCHRONIZATION = "im.quicksy.synchronization:0"
    const val AVATAR_DATA = "urn:xmpp:avatar:data"
    const val AVATAR_METADATA = "urn:xmpp:avatar:metadata"
    const val AVATAR_CONVERSION = "urn:xmpp:pep-vcard-conversion:0"
    const val JINGLE = "urn:xmpp:jingle:1"
    const val JINGLE_ERRORS = "urn:xmpp:jingle:errors:1"
    const val JINGLE_MESSAGE = "urn:xmpp:jingle-message:0"
    const val JINGLE_ENCRYPTED_TRANSPORT = "urn:xmpp:jingle:jet:0"
    const val JINGLE_ENCRYPTED_TRANSPORT_OMEMO = "urn:xmpp:jingle:jet-omemo:0"
    const val JINGLE_TRANSPORTS_S5B = "urn:xmpp:jingle:transports:s5b:1"
    const val JINGLE_TRANSPORTS_IBB = "urn:xmpp:jingle:transports:ibb:1"
    const val JINGLE_TRANSPORT_ICE_UDP = "urn:xmpp:jingle:transports:ice-udp:1"
    const val JINGLE_TRANSPORT_WEBRTC_DATA_CHANNEL =
            "urn:xmpp:jingle:transports:webrtc-datachannel:1"
    const val JINGLE_TRANSPORT = "urn:xmpp:jingle:transports:dtls-sctp:1"
    const val JINGLE_APPS_RTP = "urn:xmpp:jingle:apps:rtp:1"

    const val JINGLE_APPS_FILE_TRANSFER = "urn:xmpp:jingle:apps:file-transfer:5"
    const val JINGLE_APPS_DTLS = "urn:xmpp:jingle:apps:dtls:0"
    const val JINGLE_APPS_GROUPING = "urn:xmpp:jingle:apps:grouping:0"
    const val JINGLE_FEATURE_AUDIO = "urn:xmpp:jingle:apps:rtp:audio"
    const val JINGLE_FEATURE_VIDEO = "urn:xmpp:jingle:apps:rtp:video"
    const val JINGLE_RTP_HEADER_EXTENSIONS =
            "urn:xmpp:jingle:apps:rtp:rtp-hdrext:0"
    const val JINGLE_RTP_FEEDBACK_NEGOTIATION =
            "urn:xmpp:jingle:apps:rtp:rtcp-fb:0"
    const val JINGLE_RTP_SOURCE_SPECIFIC_MEDIA_ATTRIBUTES =
            "urn:xmpp:jingle:apps:rtp:ssma:0"
    const val IBB = "http://jabber.org/protocol/ibb"
    const val PING = "urn:xmpp:ping"
    const val PUSH = "urn:xmpp:push:0"
    const val COMMANDS = "http://jabber.org/protocol/commands"
    const val MUC_USER = "http://jabber.org/protocol/muc#user"
    const val BOOKMARKS2 = "urn:xmpp:bookmarks:1"
    const val BOOKMARKS2_COMPAT = BOOKMARKS2 + "#compat"
    const val INVITE = "urn:xmpp:invite"
    const val PARS = "urn:xmpp:pars:0"
    const val EASY_ONBOARDING_INVITE = "urn:xmpp:invite#invite"
    const val OMEMO_DTLS_SRTP_VERIFICATION =
            "http://gultsch.de/xmpp/drafts/omemo/dlts-srtp-verification"
    const val JINGLE_TRANSPORT_ICE_OPTION =
            "http://gultsch.de/xmpp/drafts/jingle/transports/ice-udp/option"
    const val UNIFIED_PUSH = "http://gultsch.de/xmpp/drafts/unified-push"
    const val USER_TUNE = "http://jabber.org/protocol/tune"
    const val VCARD4 = "urn:ietf:params:xml:ns:vcard-4.0"
    const val REPORTING = "urn:xmpp:reporting:1"
    const val REPORTING_REASON_SPAM = "urn:xmpp:reporting:spam"
    const val EPHEMERAL = "urn:xmpp:ephemeral:0"
    const val SDP_OFFER_ANSWER = "urn:ietf:rfc:3264"
    const val HASHES = "urn:xmpp:hashes:2"
    const val MDS_DISPLAYED = "urn:xmpp:mds:displayed:0"
    const val MDS_SERVER_ASSIST = "urn:xmpp:mds:server-assist:0"
    const val PUBSUB_SOCIAL_FEED = "urn:xmpp:pubsub-social-feed:1"
    const val MICROBLOG = "urn:xmpp:microblog:0"
    const val PUBSUB_STORIES = "urn:xmpp:pubsub-social-feed:stories:0"
    const val ATOM = "http://www.w3.org/2005/Atom"

    const val ENTITY_CAPABILITIES = "http://jabber.org/protocol/caps"
    const val ENTITY_CAPABILITIES_2 = "urn:xmpp:caps"
    const val LIVE_LOCATION = "urn:xmpp:live-location:0"
}
