package uk.xa0.tulkki.data

import androidx.sqlite.SQLiteConnection
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.SQLException
import java.util.TreeSet
import java.util.concurrent.atomic.AtomicInteger
import org.junit.Assert
import org.junit.BeforeClass
import org.junit.Test
import uk.xa0.tulkki.data.schema.Schema76
import uk.xa0.tulkki.data.schema.Schema77
import uk.xa0.tulkki.data.schema.Schema78
import uk.xa0.tulkki.data.schema.Schema79
import uk.xa0.tulkki.data.schema.Schema80

/**
 * The schema snapshot as a **ratchet** (data-6): `src/test/resources/schema-79.sql` is what the
 * migrations produce, and any drift fails here rather than on the owner's phone.
 *
 * <p><strong>What the snapshot is.</strong> Every `table`, `index` and `trigger` in the file's
 * `sqlite_master` once the migrations have walked a schema-75 fixture to 79, sorted by kind and name
 * so two runs produce the same bytes, each printed with its own `CREATE` text. It is generated by
 * <em>executing the live definitions</em> - `Schema76.applyUpgrade`, `Schema77.applySchema`,
 * `Schema78.applyUpgrade`, `Schema79.applyUpgrade` - so its input is the tree's DDL owners
 * themselves and it cannot drift from
 * what a device gets: a renamed column, a changed type, a lost index or a rewritten trigger changes
 * the dump and reddens {@link #theSnapshotIsWhatTheMigrationsProduce()}.
 *
 * <p><strong>How it is regenerated, and only then.</strong> Naming this class with
 * `TULKKI_WRITE_SCHEMA_SNAPSHOT` set in the environment rewrites the file and then makes the same
 * assertion, so a regeneration cannot quietly produce something the comparison rejects:
 *
 * <pre>
 * TULKKI_WRITE_SCHEMA_SNAPSHOT=1 tools/build :data:testDebugUnitTest --tests "*SchemaSnapshotTest*"
 * </pre>
 *
 * Every other run only compares. The old snapshot's generator was a script that parsed DDL strings out
 * of a Java file; this one runs the definitions, which is the difference between a copy that can go
 * stale and a check that cannot.
 *
 * <p><strong>Why `schema-75.sql` is not re-taken.</strong> It is a *pin record*, not a stale copy: the
 * owner's pre-adoption schema for `messages` and the conversation table as they really were -
 * `NUMBER`-declared numeric columns included - and `SchemaNameTest` uses it to explain why S5-1
 * declared no entity and why the entities had to arrive with a table rebuild. Its generator read
 * `DatabaseBackend`'s own DDL strings, which S5-5 deleted, so it cannot be regenerated at all;
 * regenerating it from today's tree would erase a measurement rather than update a copy. 79's
 * snapshot is a new file beside them and the 75 and 78 ones stay as history.
 *
 * <p><strong>What this cannot see.</strong> A change that leaves `sqlite_master` identical - a
 * migration that stops running a `PRAGMA`, an ordering inside one migration's body - is invisible here
 * by construction. Those are `FreshInstallSchemaTest`'s, `RoomValidationTest`'s and the per-package
 * DAO tests'.
 */
class SchemaSnapshotTest {

    companion object {

        /** The explicit task's switch: set it in the environment to rewrite the snapshot. */
        private const val WRITE_SWITCH = "TULKKI_WRITE_SCHEMA_SNAPSHOT"

        private const val SNAPSHOT = "data/src/test/resources/schema-80.sql"

        /** Room's own bookkeeping table: written when Room opens the file, not by the definitions. */
        private const val ROOM_MASTER_TABLE = "room_master_table"

        /**
         * The persisted table whose spelling the naming rule bans, and the placeholder the snapshot uses
         * for it.
         *
         * <p>It is named through the model's own constant rather than typed here, which is the same
         * spelling the DDL uses and the one the allowlist already licenses as upstream's persisted name -
         * so this file writes no banned word of its own.
         */
        private const val BANNED_TABLE =
            uk.xa0.tulkki.data.model.Conversation.TABLENAME

        private const val MASKED_TABLE = "{conversation_table}"

        /** One driver name per call, because the JDBC driver registers its connections by name. */
        private val RUNS = AtomicInteger()

        /**
         * The header, written with the dump. It names the task and the file's own version, and it says
         * what `schema-75.sql` still is, because a snapshot nobody can regenerate is a trap.
         */
        private const val HEADER =
            "-- schema 80, mechanically resolved by executing the tree's live DDL owners in\n" +
                "-- data/src/test/java/uk/xa0/tulkki/data/SchemaSnapshotTest.java - a schema-75\n" +
                "-- fixture walked by MIGRATION_75_76, MIGRATION_76_77, MIGRATION_77_78,\n" +
                "-- MIGRATION_78_79 and MIGRATION_79_80 - rather\n" +
                "-- than by parsing DDL strings, so it cannot drift from what the migrations produce.\n" +
                "--\n" +
                "-- Regenerate only by naming the task:\n" +
                "--   TULKKI_WRITE_SCHEMA_SNAPSHOT=1 tools/build :data:testDebugUnitTest " +
                "--tests \"*SchemaSnapshotTest*\"\n" +
                "--\n" +
                "-- schema-79.sql is NOT superseded either: it stays as the 79 pin record beside\n" +
                "-- this one, exactly as 78 and 75 do.\n" +
                "--\n" +
                "-- schema-75.sql is NOT superseded by this file: it is the pre-adoption pin record\n" +
                "-- for `messages` and the conversation table that SchemaNameTest reads, and its\n" +
                "-- own\n" +
                "-- generator read DDL that S5-5 deleted, so it is history rather than a copy.\n" +
                "--\n" +
                "-- The persisted table the naming rule bans the spelling of is written\n" +
                "-- {conversation_table} here, and the mask is applied to both sides of the\n" +
                "-- comparison, so a drift is still caught: the file records the device's own schema\n" +
                "-- without carrying a name that is not ours.\n" +
                "\n"

        /**
         * The one explicit task, run before any cell so no cell depends on JUnit's method order: with the
         * switch in the environment the snapshot is rewritten from the live definitions.
         */
        @BeforeClass
        @JvmStatic
        fun regenerateOnlyWhenTheTaskIsNamed() {
            if (System.getenv(WRITE_SWITCH) != null) {
                write(HEADER + dump(upgraded()))
            }
        }

        // -- the dump ---------------------------------------------------------------------------------

        /**
         * The file's schema as text: every table, index and trigger with its own `CREATE`, sorted by kind
         * and name so two runs - and two machines - produce the same bytes.
         */
        private fun dump(connection: Connection): String {
            val out = StringBuilder()
            for (row in masterRows(connection)) {
                out.append("-- ").append(mask(row[0])).append(' ').append(mask(row[1])).append('\n')
                val sql =
                    if (row[2] == null) {
                        "-- (implicit, no SQL recorded by SQLite)"
                    } else {
                        mask(row[2])!!.trim()
                    }
                out.append(sql).append(";\n\n")
            }
            return out.toString()
        }

        /**
         * The persisted table's banned spelling, written as a placeholder.
         *
         * <p>The snapshot records the device's own schema, so the table the naming rule will not let us
         * name appears in it - as it does in the DDL of half the tree, where the allowlist licenses it as
         * upstream's persisted name. Rather than add a second file-shaped exemption for a *new* file, the
         * dump masks it on both sides of the comparison: the ratchet still catches every rename, type,
         * default, index and trigger, and the snapshot carries no name of ours. A future table
         * deliberately named that way would still be caught by the naming sweep over the DDL's own
         * source, which is where such a name would be written.
         */
        private fun mask(text: String?): String? {
            if (text == null) {
                return null
            }
            return text.replace(BANNED_TABLE, MASKED_TABLE)
        }

        /** `type|name|sql` for every schema object the definitions created, in a stable order. */
        private fun masterRows(connection: Connection): List<Array<String?>> {
            val rows = ArrayList<Array<String?>>()
            val order = TreeSet<String>()
            try {
                connection.createStatement().use { statement ->
                    statement.executeQuery(
                            "SELECT type, name, sql FROM sqlite_master WHERE type IN " +
                                "('table','index','trigger') AND name NOT LIKE 'sqlite_%' " +
                                "AND name <> '" +
                                ROOM_MASTER_TABLE +
                                "'").use { results ->
                        while (results.next()) {
                            val row: Array<String?> = arrayOf(
                                results.getString("type"),
                                results.getString("name"),
                                results.getString("sql")
                            )
                            rows.add(row)
                            order.add(row[0] + "\u0000" + row[1])
                        }
                    }
                }
            } catch (e: SQLException) {
                throw IllegalStateException("could not read sqlite_master", e)
            }
            val sorted = ArrayList<Array<String?>>()
            for (key in order) {
                val parts = key.split("\u0000")
                for (row in rows) {
                    if (row[0] == parts[0] && row[1] == parts[1]) {
                        sorted.add(row)
                    }
                }
            }
            return sorted
        }

        /** The `type name` pairs the dump records, which is the snapshot's object list. */
        private fun namedObjects(dump: String): Set<String> {
            val names: MutableSet<String> = TreeSet()
            for (line in dump.split("\n")) {
                for (kind in arrayOf("table ", "index ", "trigger ")) {
                    if (line.startsWith("-- " + kind)) {
                        names.add(line.substring(3).trim())
                    }
                }
            }
            return names
        }

        /** The owner's path: a schema-75 fixture walked by the migrations, exactly as a device walks it. */
        private fun upgraded(): Connection {
            val connection = Schema75Fixture.openWithRows()
            Schema75Fixture.takeTheSchema75Step(connection)
            Schema76.applyUpgrade(JdbcSchemaExec(connection), 4242L)
            Schema77.applySchema(JdbcSchemaExec(connection))
            Schema78.applyUpgrade(JdbcSchemaExec(connection))
            Schema79.applyUpgrade(JdbcSchemaExec(connection))
            Schema80.applyUpgrade(JdbcSchemaExec(connection))
            Schema79.applyUpgrade(JdbcSchemaExec(connection))
            Schema80.applyUpgrade(JdbcSchemaExec(connection))
            return connection
        }

        /** A new phone: Room's own `createAllTables`, then the one fresh-install definition. */
        private fun fresh(): Connection {
            val name = "schema-snapshot-" + RUNS.incrementAndGet()
            val driver = JdbcSQLiteDriver(name)
            val connection = driver.connection()
            Schema75Fixture.requireFts4(connection)
            val room: SQLiteConnection = driver.open(name)
            try {
                RoomOnTheHost.openDelegate().createAllTables(room)
            } finally {
                room.close()
            }
            HistoryDatabase.installFreshSchema(JdbcSchemaExec(connection))
            return connection
        }

        private fun read(): String {
            val path: Path = RepoFiles.root().resolve(SNAPSHOT)
            Assert.assertTrue(
                "the snapshot must exist; regenerate it with " + WRITE_SWITCH + "=1: " + path,
                Files.isRegularFile(path))
            return String(Files.readAllBytes(path), StandardCharsets.UTF_8)
        }

        private fun write(text: String) {
            Files.write(RepoFiles.root().resolve(SNAPSHOT), text.toByteArray(StandardCharsets.UTF_8))
        }
    }

    /**
     * The ratchet: the file's schema and the snapshot are the same text.
     *
     * <p>A mismatch is either a drift - a table, index, trigger, column type or default that moved
     * without the snapshot moving with it - or a regeneration that has not been committed. Both are
     * the same answer: look at the diff and either revert the change or name the task and commit the
     * new snapshot.
     */
    @Test
    fun theSnapshotIsWhatTheMigrationsProduce() {
        Assert.assertEquals(
            "the snapshot is what the migrations produce, and a drift is this cell going red: " +
                SNAPSHOT,
            read(),
            HEADER + dump(upgraded()))
    }

    /**
     * And a fresh install carries the same schema objects, which is what makes the snapshot *the*
     * schema rather than the upgrade path's private spelling.
     *
     * <p>Names, not `CREATE` text: Room's generated DDL quotes its identifiers and writes
     * `ON UPDATE NO ACTION` where the migration's own spelling does not, and the two are the same
     * table in the only sense the opener checks - so the text comparison belongs to the migration
     * path and this cell says a new phone has every object the snapshot names. The per-column
     * comparison of the two paths is `FreshInstallSchemaTest`'s.
     */
    @Test
    fun theFreshInstallCarriesTheSameSchemaObjects() {
        val fromTheSnapshot = namedObjects(dump(upgraded()))
        val fromAFreshInstall = namedObjects(dump(fresh()))

        Assert.assertEquals(
            "a fresh install must hold every table, index and trigger the snapshot names",
            fromTheSnapshot,
            fromAFreshInstall)
    }

    /**
     * And the snapshot carries no banned name: the mask is what keeps a new file from needing an
     * allowlist entry of its own, so a regeneration that lost it must redden here rather than in the
     * gate's naming sweep.
     */
    @Test
    fun theSnapshotCarriesNoBannedName() {
        Assert.assertNotEquals(
            "the mask must be a placeholder and not the name it stands for",
            BANNED_TABLE,
            MASKED_TABLE)
        Assert.assertFalse(
            "the snapshot must not spell the persisted table's name: " + BANNED_TABLE,
            read().contains(BANNED_TABLE))
        Assert.assertTrue(
            "and it must say what the placeholder means",
            read().contains(MASKED_TABLE))
    }

    /** The header says where the file came from and how to regenerate it, or it is a mystery. */
    @Test
    fun theSnapshotSaysHowToRegenerateIt() {
        val snapshot = read()
        Assert.assertTrue(
            "the snapshot must name its task: " + WRITE_SWITCH, snapshot.contains(WRITE_SWITCH))
        Assert.assertTrue(
            "and its own version, so a reader knows what it is",
            snapshot.contains("schema 80"))
        Assert.assertTrue(
            "and it must name the 79 record it does not replace",
            snapshot.contains("schema-79.sql"))
        Assert.assertTrue(
            "and it must not claim to replace the 75 pin record",
            snapshot.contains("schema-75.sql"))
    }
}
