// crypto/build.gradle.kts - generated by tools/split-modules from tools/modules.toml
// namespace uk.xa0.tulkki.crypto (docs/MIGRATION.md "The module map" §4.2: R and .databinding follow the namespace, and two
// modules may not generate the same R/BuildConfig FQN)

apply(plugin = "com.android.library")

configure<com.android.build.api.dsl.LibraryExtension> {
    namespace = "uk.xa0.tulkki.crypto"
    compileSdk = 36
    defaultConfig {
        // AGP 9's public library DSL has no `targetSdk` member: the Groovy `targetSdkVersion 36`
        // here landed on the legacy `BaseFlavor.targetSdkVersion(int)` through the closure's runtime
        // delegate, and a library's AAR carries none. Left out rather than emulated - reported.
        minSdk = 23
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig = true
    }
    lint {
        disable += listOf("MissingTranslation", "InvalidPackage", "AppCompatResource")
        abortOnError = false
    }
}

dependencies {
    "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.1.5")
    "implementation"(project(":xmpp"))
    "implementation"(project(":libs:annotation"))
    "implementation"("androidx.annotation:annotation:1.9.1")
    "implementation"("com.github.open-keychain.open-keychain:openpgp-api:v5.7.1")
    "implementation"("com.google.guava:guava:33.6.0-android")
    "implementation"("org.bouncycastle:bcmail-jdk18on:1.84")
    "implementation"("org.jitsi:org.otr4j:0.23")
    "api"("org.whispersystems:signal-protocol-java:2.6.2")
    // port-16: the Argon2 implementation the row names, replacing the in-tree C + its JNI wrapper.
    // p = 4 is passed explicitly at the call site: argon2kt's default is 2, which would change the
    // database key and the encoded string with no error.
    "implementation"("com.lambdapioneer.argon2kt:argon2kt:1.6.0")
    "testImplementation"("junit:junit:4.13.2")
}
