// ui/build.gradle.kts - generated by tools/split-modules from tools/modules.toml
// namespace uk.xa0.tulkki.ui (docs/MIGRATION.md "The module map" §4.2: R and .databinding follow the namespace, and two
// modules may not generate the same R/BuildConfig FQN)

// ui-1: Compose arrives.  One flavour, one module and one compiler, so the compiler is the plugin
// `org.jetbrains.kotlin.plugin.compose` at the tree's own Kotlin version (2.3.21) and NOT a
// `kotlin { }` block: AGP 9's built-in Kotlin compiles the module's `.kt` files (docs/MIGRATION.md,
// "Compose: what the survey changed"), exactly as `data/build.gradle` applies KSP this way.
// The plugin is plugin-managed, so it is declared here and not on the root buildscript classpath.
plugins {
    id("org.jetbrains.kotlin.plugin.compose") version "2.3.21"
}

apply(plugin = "com.android.library")
apply(plugin = "com.android.compose.screenshot")

configure<com.android.build.api.dsl.LibraryExtension> {
    namespace = "uk.xa0.tulkki.ui"
    experimentalProperties["android.experimental.enableScreenshotTest"] = true
    compileSdk = 36
    defaultConfig {
        buildConfigField("String", "APPLICATION_ID", "\"${rootProject.extra["appId"]}\"")
        buildConfigField("String", "APP_NAME", "\"${rootProject.extra["appName"]}\"")
        buildConfigField("String", "PRIVACY_POLICY", "${rootProject.extra["privacyPolicy"]}")
        buildConfigField("int", "VERSION_CODE", "${rootProject.extra["versionCode"]}")
        buildConfigField("String", "VERSION_NAME", "\"${rootProject.extra["versionName"]}\"")
        // AGP 9's public library DSL has no `targetSdk` member: the Groovy `targetSdkVersion 36`
        // here landed on the legacy `BaseFlavor.targetSdkVersion(int)` through the closure's runtime
        // delegate, and a library's AAR carries none. Left out rather than emulated - reported.
        minSdk = 23
        resValue("string", "applicationId", rootProject.extra["appId"] as String)
    }
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    buildFeatures {
        buildConfig = true
        dataBinding = true
        resValues = true
        compose = true
    }
    lint {
        disable += listOf("MissingTranslation", "InvalidPackage", "AppCompatResource")
        abortOnError = false
    }
}

dependencies {
    "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.1.5")
    "screenshotTestImplementation"("com.android.tools.screenshot:screenshot-validation-api:0.0.1-alpha16")
    "screenshotTestImplementation"("androidx.compose.ui:ui-tooling")
    "implementation"(project(":crypto"))
    "implementation"(project(":data"))
    "implementation"(project(":translation"))
    "implementation"(project(":xmpp"))
    "implementation"(project(":libs:annotation"))
    "implementation"("androidx.annotation:annotation:1.9.1")
    "implementation"("androidx.core:core:1.18.0")
    // ui-1: the Compose graph.  The BOM is the one docs/MIGRATION.md "Design: the Compose UI" §1.5
    // pins material3 1.4.0 with, and the same paragraph warns to check that it resolves on the first
    // Compose build rather than trust it.  Checked: 2026.09.00 - that range's newest - maps
    // androidx.compose.ui to 1.12.1, whose AAR metadata demands minCompileSdk 37 and AGP 9.1.0, and
    // this tree is compileSdk 36 / AGP 9.0.1.  The newest BOM that both carries material3 1.4.0 and
    // resolves here is 2026.06.01: ui 1.11.4 and material3 1.4.0, both minCompileSdk 35 and
    // minAndroidGradlePluginVersion 8.6.0 (2026.08.00 is already on ui 1.12.0 and does not).
    "implementation"(platform("androidx.compose:compose-bom:2026.06.01"))
    "implementation"("androidx.compose.ui:ui")
    "implementation"("androidx.compose.material3:material3")
    // The Compose host for the Activities that already exist: every one extends AppCompatActivity,
    // so it is a ComponentActivity already and `setContent` needs no base-class swap (docs/MIGRATION.md,
    // "Compose: what the survey changed").  The BOM does not manage this artifact, so version it here.
    "implementation"("androidx.activity:activity-compose:1.13.0")
    "implementation"("androidx.emoji2:emoji2-bundled:1.6.0")
    "implementation"("androidx.emoji2:emoji2-emojipicker:1.6.0")
    "implementation"("androidx.emoji2:emoji2:1.6.0")
    "implementation"("androidx.media3:media3-exoplayer:1.10.1")
    "implementation"("androidx.media3:media3-session:1.10.1")
    "implementation"("androidx.media3:media3-ui:1.10.1")
    "implementation"("androidx.preference:preference:1.2.1")
    "implementation"("com.leinardi.android:speed-dial:3.3.0")
    "implementation"("com.squareup.okhttp3:okhttp:4.12.0")
    "implementation"("com.squareup.retrofit2:converter-gson:3.0.0")
    "implementation"("com.wefika:flowlayout:0.4.1")
    "implementation"("io.noties.markwon:core:4.6.2")
    "implementation"("androidx.appcompat:appcompat:1.7.1")
    "implementation"("androidx.browser:browser:1.10.0")
    "implementation"("androidx.cardview:cardview:1.0.0")
    "implementation"("androidx.constraintlayout:constraintlayout:2.2.1")
    "implementation"("androidx.exifinterface:exifinterface:1.4.2")
    "implementation"("androidx.recyclerview:recyclerview:1.4.0")
    "implementation"("androidx.swiperefreshlayout:swiperefreshlayout:1.2.0")
    "implementation"("androidx.viewpager:viewpager:1.1.0")
    "implementation"("androidx.work:work-runtime:2.11.2")
    "implementation"("com.caverock:androidsvg-aar:1.4")
    "implementation"("com.github.bumptech.glide:annotations:4.16.0")
    "implementation"("com.github.bumptech.glide:glide:4.16.0")
    "implementation"("com.github.chrisbanes:PhotoView:2.3.0")
    "implementation"("com.github.ipld:java-cid:v1.3.1")
    "implementation"("com.github.martin-stone:hsv-alpha-color-picker-android:3.1.0")
    "implementation"("com.github.open-keychain.open-keychain:openpgp-api:v5.7.1")
    "implementation"("com.github.singpolyma:Better-Link-Movement-Method:393d35e453")
    "implementation"("com.github.singpolyma:TokenAutoComplete:bfa93780e0")
    "implementation"("com.github.singpolyma:android-identicons:3361281bd4")
    "implementation"("com.google.android.material:material:1.14.0")
    "implementation"("com.google.guava:guava:33.6.0-android")
    "implementation"("com.google.zxing:core:3.5.4")
    "implementation"("com.kizitonwose.calendar:compose:2.10.1")
    "implementation"("com.mikepenz:materialdrawer:10.0.0-b01")
    "implementation"("com.tbuonomo:dotsindicator:5.1.0")
    "implementation"("im.conversations.webrtc:webrtc-android:129.0.0")
    "implementation"("io.michaelrocks:libphonenumber-android:8.13.52")
    "implementation"("me.drakeet.support:toastcompat:1.1.0")
    "implementation"("net.fellbaum:jemoji:1.7.6")
    "implementation"("org.jitsi:org.otr4j:0.23")
    "implementation"("org.osmdroid:osmdroid-android:6.1.20")
    "implementation"("org.whispersystems:signal-protocol-java:2.6.2")
    "implementation"("com.github.CanHub:Android-Image-Cropper:4.5.0")
    "testImplementation"("junit:junit:4.13.2")
    "testImplementation"("org.junit.jupiter:junit-jupiter:5.12.2")
    "testImplementation"("com.squareup.okhttp3:mockwebserver:4.12.0")
}

// ui-11: section 7.1 calls `validateDebugScreenshotTest` "the gate", while the repo's gate is
// `tools/verify`, whose JVM step is the library modules' `testDebugUnitTest`.  Hanging the validation
// on that task is the smallest way to make a pixel difference fail the suite without inventing a sixth
// check in tools/verify - and the screenshot engine writes its own JUnit XML under
// `build/test-results/validateDebugScreenshotTest/`, so the unit-test report the floor is counted from
// is untouched.  The name is the plugin's, measured on this tree; `matching`/`configureEach` rather
// than `tasks.named` because AGP creates the unit-test tasks after this script has been evaluated.
tasks.matching { it.name == "testDebugUnitTest" }.configureEach {
    dependsOn("validateDebugScreenshotTest")
}
